// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4wfo_bXKCmrl_N_4qUqSYkpkaFbBGkkY',
    appId: '1:996169362231:web:314982b30584621f42c8b2',
    messagingSenderId: '996169362231',
    projectId: 'fir-flutter-43c1d',
    authDomain: 'fir-flutter-43c1d.firebaseapp.com',
    storageBucket: 'fir-flutter-43c1d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCajFp5cxJnrHuUJ41TXr2oKKTZoJZ5xU',
    appId: '1:996169362231:android:e94e863677a56a9042c8b2',
    messagingSenderId: '996169362231',
    projectId: 'fir-flutter-43c1d',
    storageBucket: 'fir-flutter-43c1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCutiLA8h4RRDpSiSoKBZdPGH-iMP1zyrw',
    appId: '1:996169362231:ios:260db545e00dd8a442c8b2',
    messagingSenderId: '996169362231',
    projectId: 'fir-flutter-43c1d',
    storageBucket: 'fir-flutter-43c1d.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCutiLA8h4RRDpSiSoKBZdPGH-iMP1zyrw',
    appId: '1:996169362231:ios:1fe0d121e49da4e942c8b2',
    messagingSenderId: '996169362231',
    projectId: 'fir-flutter-43c1d',
    storageBucket: 'fir-flutter-43c1d.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
